fix(hand tracking): fix event order when using hands and hide hands i…
pmndrs/react-xr pull request #283
Opened 2023-07-05 13:03 UTC by Ledzz

Fixes #273

2023-07-05 14:21 UTC, saitonakamura requested changes

2023-07-05 14:21 UTC, saitonakamura commented on src/OculusHandModel.ts
> +  private _onDisconnected: EventListener<Event, 'disconnected', Object3D<Event>> = () => {
**suggestion:** lets's also add `if (xrInputSource.hand` guard to not to accidently clear it if some non hand-related disconnect event creeps in

2023-07-05 14:21 UTC, saitonakamura commented on src/OculusHandModel.ts
> +    this.clear()
**suggestion:** this code looks similar to what happens in `_onDisconnected`, maybe let's extract it as a private method of a class and reuse it?

2023-07-05 14:21 UTC, saitonakamura commented on src/XRHandMeshModel.ts
> +    if (allInvisible && this.scene) {
**suggestion:** we may want to add a comment explaining why we do it?

2023-07-06 07:39 UTC, saitonakamura approved these changes
awesome work!

2023-07-06 07:43 UTC, saitonakamura commented
@Ledzz let's test examples on codesandbox and report here

2023-07-06 09:12 UTC, Ledzz commented
@saitonakamura they all seem to work fine, except player demo, it can't load hdr map, so I guess its unrelated to this code

2023-07-06 10:55 UTC, merged